version: "3.8"
services:
  # Prisma uses this database to detect schema drift and other dev checks
  # See https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database
  supabase-shadow:
    image: supabase/postgres
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    container_name: supabase-shadow-db
    restart: unless-stopped
    ports:
      - "12345:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      # 👇 Change this volume mapping to something that makes sense for you
      - ./postgres-data:/var/lib/postgresql/data
